######################
#### KEYBINDINGS #####
######################

# Remap command prefix to ctrl + b -> ctrl + a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Intuitive window splits - and |
bind | split-window -h
bind - split-window -v
unbind '"'
unbind % 

# Prefix r to reload tmux config
bind r source-file ~/.tmux.conf \; display-message "Config reloaded."

# Pane navigation with arrow keys
bind h select-pane -L
bind j select-pane -U
bind k select-pane -D
bind l select-pane -R

# Pane resizing with prefix and hold
bind -r Left resize-pane -L 1
bind -r Right resize-pane -R 1
bind -r Up resize-pane -U 1
bind -r Down resize-pane -D 1

# Visual selection and copying
set-window-option -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind P paste-buffer
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"

#########################
### GENERAL BEHAVIOUR ###
#########################

# Bigger message history
set -g history-limit 20000

######################
### DESIGN CHANGES ###
######################

# Don't notify me ever
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# Some colour combinations I like
# bg = colour0 (black) or colour22 (dark green)
# fg = colour253 (light grey) or colour15 (white)
# highlight = colour135 (medium purple) or 183 (plum 2)
# lowlight = colour59 (dark grey)
# allows colour passthrough from shell

# Commands run in sequence; put desired theme at bottom

# Theme: Poker Table
set -g window-style 'bg=colour22,fg=colour15'
set -g window-active-style 'bg=colour22,fg=colour15'
set -g pane-border-style 'bg=colour22, fg=colour15'
set -g pane-active-border-style 'bg=colour22, fg=colour15'

set -g status-style 'bg=colour22, fg=colour135'
set -g window-status-current-style 'bg=colour135, fg=colour0'
setw -g window-status-format ' #I #[fg=colour0]#W #[fg=colour0]#F '

setw -g window-status-bell-style 'bg=colour135 fg=colour15 bold'
set -g message-style 'bg=colour22 fg=colour15 bold'
setw -g mode-style "bg=colour135,fg=colour22"

# Theme: Midnight
set -g window-style 'bg=colour0,fg=colour253'
set -g window-active-style 'bg=colour0,fg=colour253'
set -g pane-border-style 'bg=colour0, fg=colour253'
set -g pane-active-border-style 'bg=colour0, fg=colour253'

set -g status-style 'bg=colour0, fg=colour135'
set -g window-status-style 'bg=colour0, fg=colour135'
set -g window-status-current-style 'bg=colour135, fg=colour253' 
setw -g window-status-format ' #W '
setw -g window-status-current-format ' #W '
set -g message-style 'bg=colour0, fg=colour253 bold'
setw -g window-status-bell-style 'bg=colour135, fg=colour253, bold'
setw -g mode-style "bg=colour59,fg=colour15"

# Message and commands
set -g status-position top
set -g status-justify left
set -g status-left ''
set -g status-right '%Y-%m-%d %H:%M '
set -g status-right-length 50
set -g status-left-length 10
