###################
#### CONTROLS #####
###################

# Remap command prefix to ctrl + b -> ctrl + a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Intuitive window splits - and | 
# Open new panes in current path
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind % 

# Prefix r to reload tmux config
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded."

# Pane navigation with arrow keys
bind h select-pane -L
bind j select-pane -U
bind k select-pane -D
bind l select-pane -R

# Pane resizing with prefix and hold
bind -r Left resize-pane -L 1
bind -r Right resize-pane -R 1
bind -r Up resize-pane -U 1
bind -r Down resize-pane -D 1

# Visual selection and copying
set-window-option -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind P paste-buffer
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"

#########################
### GENERAL BEHAVIOUR ###
#########################

# Bigger message history
set -g history-limit 20000

# Shorter command delay
set -sg escape-time 1


# Always present panes as tmux's own terminal type to applications.
set -g default-terminal "tmux-256color"

# Advertise truecolor for common cross-platform terms in case someone else wants dotfiles
set-option -sa terminal-features ",xterm*:RGB,xterm-rio:RGB,alacritty*:RGB,wezterm:RGB,foot*:RGB,kitty:RGB,tmux-256color:RGB"
set-option -ga terminal-overrides ",xterm*:Tc,xterm-rio:Tc,alacritty*:Tc,wezterm:Tc,foot*:Tc,kitty:Tc,tmux-256color:Tc"

######################
### DESIGN CHANGES ###
######################

# Using cattpuccin mocha for themeing, extend theming from status bar to panes
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin-tmux_show_git 0
set -g @catppuccin-tmux_pane_id_style hide 
set -g @catppuccin-tmux_zoom_id_style hide 
set -g @catppuccin-tmux_show_path 1
run $HOME/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# Keep active pane border foreground identical to inactive panes
set -g pane-border-style "fg=#{@thm_surface_0}"
set -g pane-active-border-style "fg=#{@thm_surface_0}"

# Don't notify me ever
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# Message and commands
set -g status-position top

# Remove floating status text
set -g status-left ""

# Remove clock
set -g status-right ""
